enum type {
    SWITCH_LEFT_DRAWER_VISIBLE = "SWITCH_LEFT_DRAWER_VISIBLE",
    CHANGE_SCHEDULE_REGISTER_VISIBLE = "CHANGE_SCHEDULE_REGISTER_VISIBLE",
    CHANGE_SCHEDULE_VIEWER_VISIBLE = "CHANGE_SCHEDULE_VIEWER_VISIBLE",
}

export default type;