enum type {
    LEFT_DRAWER_VISIBLE = "LEFT_DRAWER_VISIBLE",
    SCHEDULE_REGISTER_VISIBLE = "SCHEDULE_REGISTER_VISIBLE",
    SCHEDULE_VIEWER_VISIBLE = "SCHEDULE_VIEWER_VISIBLE",
}

export default type;